### ISSUE TITLE
Error in execute - unused argument

### ISSUE THREAD

**Issue by lucid0921** [ohdsi-studies/RanitidineCancerRisk#21]
execute 구문 실행 시 아래와 같은 에러메세지가 나옵니다.
unused argument (onTreatmentWithBlankingPeriod = TRUE) 

![image](https://user-images.githubusercontent.com/34934336/82780108-151ead80-9e91-11ea-9a45-ea497de18504.png)

**Comment by chandryou** [comment]
Solved
