### ISSUE TITLE
Adding ITT analysis

### ISSUE THREAD

**Issue by chandryou** [ohdsi-studies/RanitidineCancerRisk#3]
@drminssi 의견: ITT 분석 추가 필요

**Comment by drminssi** [comment]
이전 gastric ulcer제외한 이유가 뭐였죠?

**Comment by chandryou** [comment]
@drminssi 
1. gastric ulcer 가 매칭이 잘 되지 않았고,
2. gastric ulcer 가 hidden malignancy 일수도 있다고 생각했기 때문입니다~

**Comment by drminssi** [comment]
넵 ~ 아참 그리고 논문쓸때 약물 복용한 평균이나 median 값이 필요하지 않을지요~ (cohort days)
근데 characterization 잘 안되더라구요,;;

**Comment by chandryou** [comment]
박찬혁 교수님 의견:

On-treatment / ITT setting 으로 나누어 분석을 하셨는데,
맥락 상 제가 이해하기로는, On-treatment 는 H2RA를 처방받는 기간 중에 암이 발생한 경우를 event 로 잡고,
ITT 는 H2RA를 복용했던 환자가 H2RA 처방받지 않는 기간 중에 암이 발생한 경우도 event 로 잡아 분석했다는 의미인 것 같은데.... 제가 이해한 바가 맞나요??

암은 기본적으로 만성질환이기 때문에, H2RA를 처방받지 않는 기간에 발생한 것 까지 event로 잡게 되는  ITT 분석이 훨씬 의미가 클 것 같습니다.

또, 위험에 노출된 후 일정기간이 지나 암이 발생한 경우만 event로 잡는 것도 고려해 주시면 좋을 듯 합니다..
예컨대, ranitidine 을 복용을 시작한지 (1개월을 먹었든, 1년을 먹었든, 5년을 먹었든 상관 없이...) 3년이내에 암이 발생한 경우는 암 발생으로 간주하지 않는 식입니다.. 왠만한 발암물질이라도 노출이 된 후 임상적으로 cancer가 진단되기까지는 3년정도의 시간은 필요하다는 가정을 깔고 있는 것이지요..
물론, 이 3년이라는 시점은 연구자가 정하게 됩니다. 많은 암종에서 우리가 biology 를 충분히 이해하고 있지 못하고 있기 때문에 이 시점을 몇 년으로 해야 하는가는 정립된 바는 없습니다..(일반적으로 대장암은 돌연변이가 시작된 후 대장암이 발견되기까지 최소 5~10년을 봅니다만.. 당연히 이 기간은 암종마다 다 다를 것이고, 같은 대장암이라 하더라도 조직학형에 따라 기간은 달라질 수 있어서...결국 연구자가 정해서 진행할 수 밖에는 없습니다..) 
개인적으로는 이 기간을 1년으로 잡는 건 너무 짧다고 생각이 듭니다만, 3년으로 잡으면 event수가 줄어들어 유의한 결과물을 내기가 어려울 수 있으므로... 1년이나 3년 정도로 다양하게 기간을 설정해서 결과를 살펴보면 어떨까 합니다.

**Comment by chandryou** [comment]
Primary setting: on-treatment + 3yr (blanking period 30d)
on-treatment + 1yr
on-treatment + 3yr
ITT

blanking period: 0 / 30d / 1yr
