### ISSUE TITLE
Execution error

### ISSUE THREAD

**Issue by solie** [ohdsi-studies/RanitidineCancerRisk#34]
Thread: Main
Message:  non-character argument
Level:  FATAL
Time:  2022-04-19 14:30:35

Stack trace:
8: h(simpleError(msg, call))
7: .handleSimpleError(function (condition) 
{
    
6: strsplit(excludeConceptIds, split = ";")
5: FUN(X[[i]], ...)
4: lapply(1:nrow(tcs), createTco)
3: createTcos(outputFolder = outputFolder, conne
2: runCohortMethod(connectionDetails = connectio
1: execute(connectionDetails = connectionDetails

R version:
R version 4.1.3 (2022-03-10)

Platform:
x86_64-pc-linux-gnu

Attached base packages:
- stats
- graphics
- grDevices
- utils
- datasets
- methods
- base

Other attached packages:
- RanitidineCancerRisk (0.5)
- DatabaseConnector (5.0.2)

**Comment by chandryou** [comment]
Thank you for reporting the error. 

Unfortunately, I cannot identify the cause of this error. 
Could you send the log.txt file to me: seng.chan.you@ohdsi.org
There is no sensitive data in the log file. 
@solie
